# Generated by Django 5.2.7 on 2025-10-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('email', models.TextField(max_length=100)),
                ('experiencia', models.TextField(max_length=500)),
                ('ult_escolaridade', models.CharField(max_length=1)),
            ],
        ),
    ]
