# Generated by Django 5.2.7 on 2025-11-02 02:08

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('user_type', models.CharField(choices=[('candidato', 'Candidato'), ('empresa', 'Empresa')], default='candidato', max_length=10, verbose_name='Tipo de Usuário')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCandidato',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'candidato'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('pretensao_salarial', models.IntegerField(blank=True, choices=[(1, 'Até 1.000'), (2, 'De 1.000 a 2.000'), (3, 'De 2.000 a 3.000'), (4, 'Acima de 3.000')], null=True, verbose_name='Pretensão Salarial')),
                ('experiencia', models.TextField(blank=True, null=True, verbose_name='Experiência')),
                ('ultima_escolaridade', models.IntegerField(blank=True, choices=[(1, 'Ensino fundamental'), (2, 'Ensino médio'), (3, 'Tecnólogo'), (4, 'Ensino Superior'), (5, 'Pós/MBA/Mestrado'), (6, 'Doutorado')], null=True, verbose_name='Última Escolaridade')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vaga', models.CharField(max_length=255, verbose_name='Nome da Vaga')),
                ('faixa_salarial', models.IntegerField(choices=[(1, 'Até 1.000'), (2, 'De 1.000 a 2.000'), (3, 'De 2.000 a 3.000'), (4, 'Acima de 3.000')], verbose_name='Faixa Salarial')),
                ('requisitos', models.TextField(verbose_name='Requisitos')),
                ('escolaridade_minima', models.IntegerField(choices=[(1, 'Ensino fundamental'), (2, 'Ensino médio'), (3, 'Tecnólogo'), (4, 'Ensino Superior'), (5, 'Pós/MBA/Mestrado'), (6, 'Doutorado')], verbose_name='Escolaridade Mínima')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('empresa', models.ForeignKey(limit_choices_to={'user_type': 'empresa'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('candidato', models.ForeignKey(limit_choices_to={'user_type': 'candidato'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidato.vaga', verbose_name='Vaga')),
            ],
        ),
    ]
