# Generated by Django 5.2.7 on 2025-10-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='experiencia',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
