# Generated by Django 5.2.7 on 2025-10-27 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_alter_usuarios_email_alter_usuarios_experiencia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
